### ISSUE TITLE
Sort stations by name

### ISSUE THREAD

**Issue by outlying** [SmokSmog/smoksmog-android#104]
Currently, stations are sort in "server order" it seems reasonable to sort them by name. However, application is mostly used in Kraków and southern Poland, take that into account, our biggest users group is in Kraków.

**Comment by Ciechosz** [comment]
A more general solution would be (at least optional) sorting by distance from current position.

**Comment by outlying** [comment]
Already deployed to Google Play Store in cfba32e (v1.9.6.196014)
