### ISSUE TITLE
Add support for PM2,5 data

### ISSUE THREAD

**Issue by outlying** [SmokSmog/smoksmog-android#107]
To have application backward compatible we will use custom header to ask server for PM2,5 data.

Header (with value):
`X-Smog-AdditionalMeasurements: pm25`

**Comment by damiankras** [comment]
Why we should use custom header?
Previously in initial release all client application supported PM2.5. 
When troubles came in we decided to turn it off on server side, so why we just turn on it again?
It shouldn't be any problem with including PM2.5

**Comment by outlying** [comment]
Long story short: we need PM2,5 , we are the only app without PM2,5 , we got very low scores from users because of that. We believe it won't get us into troubles again but we need to support it differently because currents apps are not ready to handle PM2,5 data
