### ISSUE TITLE
Fix issue with HistoryActivity

### ISSUE THREAD

**Issue by outlying** [SmokSmog/smoksmog-android#23]
Where is Activity creation problem, Activity is created with null data, button history should not be enabled until data is loaded, and creation process should be in static method on HistoryActivity and should check if data given for creation is valid, more

https://www.fabric.io/smoksmog2/android/apps/pl.malopolska.smoksmog/issues/567e85b9f5d3a7f76ba8bbd7

ask for access

**Comment by kamilzych** [comment]
Fixed by merging #24
